"""
Add remaining domains: Financial Documents, Newspaper, Comparison, and Final Analysis
"""

import json

# Load existing notebook
with open('NLP.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Cell 12: Domain 3 - Financial Document Analysis
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 🏢 8. Domain 3: Financial Document Analysis\n",
        "\n",
        "### NLP Techniques: Financial Metrics Extraction, Risk Detection, Red Flag Identification\n",
        "\n",
        "Analyzing annual reports, financial statements, and corporate documents."
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Sample financial document text\n",
        "financial_doc_text = \"\"\"\n",
        "The company reported revenue of Rs. 15,250 crore for FY 2023-24, up 12% YoY.\n",
        "Net profit stood at Rs. 2,340 crore with a profit margin of 15.3 percent.\n",
        "EBITDA increased to Rs. 3,890 crore, representing an EBITDA margin of 25.5%.\n",
        "Total assets grew to Rs. 45,600 crore while liabilities were Rs. 28,900 crore.\n",
        "Debt-to-equity ratio improved to 0.85 from 1.12 last year.\n",
        "Return on equity (ROE) was 18.2 percent, above industry average.\n",
        "Operating cash flow was Rs. 3,200 crore, showing strong liquidity.\n",
        "\n",
        "Risk Factors:\n",
        "The company faces regulatory challenges in key markets.\n",
        "Currency fluctuations may impact international revenues.\n",
        "Competition from new entrants poses market share risks.\n",
        "Supply chain disruptions could affect production schedules.\n",
        "Cybersecurity threats remain a concern for digital operations.\n",
        "\n",
        "Management Discussion:\n",
        "The board approved a dividend of Rs. 12 per share.\n",
        "Capital expenditure of Rs. 2,500 crore planned for expansion.\n",
        "Focus on digital transformation and automation initiatives.\n",
        "Strategic partnerships announced with three global firms.\n",
        "Sustainability goals include 50% renewable energy by 2025.\n",
        "\"\"\"\n",
        "\n",
        "# Process financial document\n",
        "fin_doc_sentences = segment_sentences(normalize_text(clean_text(financial_doc_text, \"English\")), \"English\")\n",
        "fin_doc_data = extract_financial_doc_data(fin_doc_sentences)\n",
        "\n",
        "print(\"\\n🏢 FINANCIAL DOCUMENT EXTRACTION RESULTS\")\n",
        "print(\"=\" * 70)\n",
        "print(f\"Financial Metrics Extracted: {len(fin_doc_data.get('metrics', []))}\")\n",
        "print(f\"Risk Factors Identified: {len(fin_doc_data.get('risks', []))}\")\n",
        "print(f\"Red Flags Detected: {len(fin_doc_data.get('red_flags', []))}\")\n",
        "print(f\"Management Highlights: {len(fin_doc_data.get('management_discussion', []))}\")\n",
        "\n",
        "# Display financial metrics\n",
        "metrics = fin_doc_data.get('metrics', [])\n",
        "if metrics:\n",
        "    print(\"\\n💹 KEY FINANCIAL METRICS:\")\n",
        "    metrics_df = pd.DataFrame(metrics)\n",
        "    print(metrics_df.to_string(index=False))\n",
        "\n",
        "# Display risks\n",
        "risks = fin_doc_data.get('risks', [])\n",
        "if risks:\n",
        "    print(\"\\n⚠️ IDENTIFIED RISK FACTORS:\")\n",
        "    for i, risk in enumerate(risks[:5], 1):\n",
        "        print(f\"{i}. {risk.get('risk_description', '')}\")\n",
        "\n",
        "# Visualizations\n",
        "fig = make_subplots(\n",
        "    rows=2, cols=2,\n",
        "    subplot_titles=('Financial Metrics Overview', 'Risk Category Distribution',\n",
        "                    'Profitability Ratios', 'Red Flags vs Normal Indicators'),\n",
        "    specs=[[{'type': 'bar'}, {'type': 'pie'}],\n",
        "           [{'type': 'indicator'}, {'type': 'bar'}]]\n",
        ")\n",
        "\n",
        "# Chart 1: Financial metrics\n",
        "if metrics:\n",
        "    metric_names = [m['metric_name'] for m in metrics[:8]]\n",
        "    metric_values = [float(m.get('value', 0)) for m in metrics[:8]]\n",
        "    fig.add_trace(\n",
        "        go.Bar(x=metric_names, y=metric_values, marker_color='lightgreen'),\n",
        "        row=1, col=1\n",
        "    )\n",
        "\n",
        "# Chart 2: Risk distribution\n",
        "if risks:\n",
        "    risk_categories = [r.get('category', 'Other') for r in risks]\n",
        "    risk_counts = Counter(risk_categories)\n",
        "    fig.add_trace(\n",
        "        go.Pie(labels=list(risk_counts.keys()), values=list(risk_counts.values())),\n",
        "        row=1, col=2\n",
        "    )\n",
        "\n",
        "# Chart 3: Profitability gauge\n",
        "profit_margin = 15.3  # Example from text\n",
        "fig.add_trace(\n",
        "    go.Indicator(\n",
        "        mode=\"gauge+number+delta\",\n",
        "        value=profit_margin,\n",
        "        title={'text': \"Profit Margin %\"},\n",
        "        delta={'reference': 12},\n",
        "        gauge={\n",
        "            'axis': {'range': [0, 30]},\n",
        "            'bar': {'color': \"darkgreen\"},\n",
        "            'steps': [\n",
        "                {'range': [0, 10], 'color': \"lightgray\"},\n",
        "                {'range': [10, 20], 'color': \"lightblue\"},\n",
        "                {'range': [20, 30], 'color': \"lightgreen\"}]\n",
        "        }\n",
        "    ),\n",
        "    row=2, col=1\n",
        ")\n",
        "\n",
        "# Chart 4: Red flags vs normal\n",
        "red_flags = fin_doc_data.get('red_flags', [])\n",
        "flag_counts = {'Red Flags': len(red_flags), 'Normal Indicators': len(metrics) - len(red_flags)}\n",
        "fig.add_trace(\n",
        "    go.Bar(x=list(flag_counts.keys()), y=list(flag_counts.values()),\n",
        "           marker_color=['red', 'green']),\n",
        "    row=2, col=2\n",
        ")\n",
        "\n",
        "fig.update_layout(height=900, showlegend=False,\n",
        "                  title_text=\"Financial Document Analysis\")\n",
        "fig.show()\n",
        "\n",
        "print(f\"\\n✅ Financial health score: {fin_doc_data.get('health_score', 75)}/100\")"
    ]
})

# Cell 13: Domain 4 - Newspaper Analysis
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 📰 9. Domain 4: Newspaper Analysis\n",
        "\n",
        "### NLP Techniques: Topic Modeling, Event Extraction, Bias Detection, Category Classification\n",
        "\n",
        "Analyzing news articles for entities, events, sentiment, and potential bias."
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Sample newspaper text\n",
        "newspaper_text = \"\"\"\n",
        "Prime Minister Narendra Modi inaugurated the new Parliament building in New Delhi yesterday.\n",
        "The ceremony was attended by President Droupadi Murmu and several cabinet ministers.\n",
        "Opposition parties boycotted the event, citing concerns about democratic traditions.\n",
        "\n",
        "In economic news, the Reserve Bank of India kept interest rates unchanged at 6.5 percent.\n",
        "RBI Governor Shaktikanta Das emphasized the need to control inflation while supporting growth.\n",
        "Stock markets rallied with Sensex gaining 450 points to close at 65,280.\n",
        "\n",
        "India's cricket team defeated Australia by 6 wickets in the World Cup final.\n",
        "Captain Rohit Sharma scored a brilliant century, leading India to victory.\n",
        "This is India's third World Cup title, sparking celebrations across the nation.\n",
        "\n",
        "Technology giant Google announced a new AI research center in Bangalore.\n",
        "The facility will employ 2,000 engineers focusing on machine learning and AI safety.\n",
        "This investment highlights India's growing importance in global tech innovation.\n",
        "\n",
        "Climate activists protested outside the Environment Ministry demanding stronger action.\n",
        "They called for immediate measures to reduce carbon emissions and protect forests.\n",
        "The government assured that new environmental policies are under consideration.\n",
        "\"\"\"\n",
        "\n",
        "# Process newspaper text\n",
        "news_sentences = segment_sentences(normalize_text(clean_text(newspaper_text, \"English\")), \"English\")\n",
        "newspaper_data = extract_newspaper_data(news_sentences)\n",
        "\n",
        "print(\"\\n📰 NEWSPAPER ANALYSIS RESULTS\")\n",
        "print(\"=\" * 70)\n",
        "print(f\"Named Entities Extracted: {len(newspaper_data.get('entities', {}).get('persons', [])) + len(newspaper_data.get('entities', {}).get('organizations', []))}\")\n",
        "print(f\"Events Identified: {len(newspaper_data.get('events', []))}\")\n",
        "print(f\"Categories Detected: {len(newspaper_data.get('categories', []))}\")\n",
        "print(f\"Bias Indicators: {len(newspaper_data.get('bias_indicators', []))}\")\n",
        "\n",
        "# Display entities\n",
        "entities_news = newspaper_data.get('entities', {})\n",
        "print(\"\\n👥 NAMED ENTITIES:\")\n",
        "print(f\"Persons: {entities_news.get('persons', [])[:10]}\")\n",
        "print(f\"Organizations: {entities_news.get('organizations', [])[:10]}\")\n",
        "print(f\"Locations: {entities_news.get('locations', [])[:10]}\")\n",
        "\n",
        "# Display events\n",
        "events = newspaper_data.get('events', [])\n",
        "if events:\n",
        "    print(\"\\n🎭 KEY EVENTS:\")\n",
        "    for i, event in enumerate(events[:5], 1):\n",
        "        print(f\"{i}. {event.get('event_description', '')}\")\n",
        "\n",
        "# Display categories\n",
        "categories = newspaper_data.get('categories', [])\n",
        "if categories:\n",
        "    print(\"\\n📂 ARTICLE CATEGORIES:\")\n",
        "    cat_counts = Counter(categories)\n",
        "    for cat, count in cat_counts.most_common():\n",
        "        print(f\"  {cat}: {count} articles\")\n",
        "\n",
        "# Visualizations\n",
        "fig = make_subplots(\n",
        "    rows=2, cols=2,\n",
        "    subplot_titles=('Entity Type Distribution', 'News Categories',\n",
        "                    'Top Mentioned Entities', 'Sentiment by Category'),\n",
        "    specs=[[{'type': 'bar'}, {'type': 'pie'}],\n",
        "           [{'type': 'bar'}, {'type': 'bar'}]]\n",
        ")\n",
        "\n",
        "# Chart 1: Entity types\n",
        "entity_counts = {\n",
        "    'Persons': len(entities_news.get('persons', [])),\n",
        "    'Organizations': len(entities_news.get('organizations', [])),\n",
        "    'Locations': len(entities_news.get('locations', [])),\n",
        "    'Events': len(events)\n",
        "}\n",
        "fig.add_trace(\n",
        "    go.Bar(x=list(entity_counts.keys()), y=list(entity_counts.values()),\n",
        "           marker_color='lightblue'),\n",
        "    row=1, col=1\n",
        ")\n",
        "\n",
        "# Chart 2: Categories pie\n",
        "if categories:\n",
        "    cat_counts = Counter(categories)\n",
        "    fig.add_trace(\n",
        "        go.Pie(labels=list(cat_counts.keys()), values=list(cat_counts.values())),\n",
        "        row=1, col=2\n",
        "    )\n",
        "\n",
        "# Chart 3: Top entities\n",
        "all_entities = (entities_news.get('persons', []) + \n",
        "                entities_news.get('organizations', []))[:10]\n",
        "entity_freq = Counter(all_entities)\n",
        "if entity_freq:\n",
        "    fig.add_trace(\n",
        "        go.Bar(y=list(entity_freq.keys()), x=list(entity_freq.values()),\n",
        "               orientation='h', marker_color='lightgreen'),\n",
        "        row=2, col=1\n",
        "    )\n",
        "\n",
        "# Chart 4: Sentiment by category\n",
        "if categories:\n",
        "    # Simulate sentiment scores for categories\n",
        "    cat_sentiment = {cat: np.random.uniform(0.3, 0.8) for cat in set(categories)}\n",
        "    fig.add_trace(\n",
        "        go.Bar(x=list(cat_sentiment.keys()), y=list(cat_sentiment.values()),\n",
        "               marker_color='coral'),\n",
        "        row=2, col=2\n",
        "    )\n",
        "\n",
        "fig.update_layout(height=900, showlegend=False,\n",
        "                  title_text=\"Newspaper Analysis - Comprehensive View\")\n",
        "fig.show()\n",
        "\n",
        "# Bias detection\n",
        "bias_indicators = newspaper_data.get('bias_indicators', [])\n",
        "if bias_indicators:\n",
        "    print(\"\\n⚖️ BIAS DETECTION:\")\n",
        "    for indicator in bias_indicators[:3]:\n",
        "        print(f\"  • {indicator}\")\n",
        "else:\n",
        "    print(\"\\n⚖️ BIAS DETECTION: No significant bias detected\")"
    ]
})

# Cell 14: Domain 5 - Budget Comparison
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 🔄 10. Domain 5: Budget Comparison Analysis\n",
        "\n",
        "### NLP Techniques: Comparative Analysis, Change Detection, Trend Identification\n",
        "\n",
        "Comparing two budget documents to identify changes, trends, and policy shifts."
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Simulate comparison between two budgets\n",
        "print(\"\\n🔄 BUDGET COMPARISON ANALYSIS\")\n",
        "print(\"=\" * 70)\n",
        "print(\"Comparing Budget 2023-24 vs Budget 2024-25\\n\")\n",
        "\n",
        "# Sample comparison data\n",
        "comparison_data = {\n",
        "    'sector_changes': [\n",
        "        {'sector': 'Agriculture', 'budget_2023': 125000, 'budget_2024': 152000, 'change_pct': 21.6},\n",
        "        {'sector': 'Education', 'budget_2023': 112000, 'budget_2024': 125000, 'change_pct': 11.6},\n",
        "        {'sector': 'Healthcare', 'budget_2023': 79000, 'budget_2024': 89155, 'change_pct': 12.9},\n",
        "        {'sector': 'Defence', 'budget_2023': 585000, 'budget_2024': 621000, 'change_pct': 6.2},\n",
        "        {'sector': 'Infrastructure', 'budget_2023': 240000, 'budget_2024': 275000, 'change_pct': 14.6},\n",
        "        {'sector': 'Railways', 'budget_2023': 225000, 'budget_2024': 255000, 'change_pct': 13.3},\n",
        "        {'sector': 'Rural Development', 'budget_2023': 145000, 'budget_2024': 160000, 'change_pct': 10.3},\n",
        "        {'sector': 'Digital India', 'budget_2023': 14000, 'budget_2024': 18000, 'change_pct': 28.6},\n",
        "    ],\n",
        "    'fiscal_changes': [\n",
        "        {'indicator': 'Fiscal Deficit (% of GDP)', 'value_2023': 5.8, 'value_2024': 5.1, 'change': -0.7},\n",
        "        {'indicator': 'Capital Expenditure (Lakh Cr)', 'value_2023': 10.0, 'value_2024': 11.11, 'change': 1.11},\n",
        "        {'indicator': 'Total Budget (Lakh Cr)', 'value_2023': 45.0, 'value_2024': 47.66, 'change': 2.66},\n",
        "        {'indicator': 'Tax Revenue (Lakh Cr)', 'value_2023': 23.3, 'value_2024': 26.02, 'change': 2.72},\n",
        "    ]\n",
        "}\n",
        "\n",
        "# Create comparison DataFrames\n",
        "sector_comp_df = pd.DataFrame(comparison_data['sector_changes'])\n",
        "fiscal_comp_df = pd.DataFrame(comparison_data['fiscal_changes'])\n",
        "\n",
        "print(\"📊 SECTOR-WISE ALLOCATION COMPARISON:\")\n",
        "print(sector_comp_df.to_string(index=False))\n",
        "\n",
        "print(\"\\n📈 FISCAL INDICATORS COMPARISON:\")\n",
        "print(fiscal_comp_df.to_string(index=False))\n",
        "\n",
        "# Comprehensive comparison visualizations\n",
        "fig = make_subplots(\n",
        "    rows=3, cols=2,\n",
        "    subplot_titles=('Sector Allocation: 2023 vs 2024', 'Percentage Change by Sector',\n",
        "                    'Fiscal Indicators Comparison', 'Budget Growth Trend',\n",
        "                    'Top Gainers and Losers', 'Overall Budget Distribution'),\n",
        "    specs=[[{'type': 'bar'}, {'type': 'bar'}],\n",
        "           [{'type': 'bar'}, {'type': 'scatter'}],\n",
        "           [{'type': 'bar'}, {'type': 'pie'}]]\n",
        ")\n",
        "\n",
        "# Chart 1: Side-by-side comparison\n",
        "fig.add_trace(\n",
        "    go.Bar(name='2023-24', x=sector_comp_df['sector'], y=sector_comp_df['budget_2023'],\n",
        "           marker_color='lightblue'),\n",
        "    row=1, col=1\n",
        ")\n",
        "fig.add_trace(\n",
        "    go.Bar(name='2024-25', x=sector_comp_df['sector'], y=sector_comp_df['budget_2024'],\n",
        "           marker_color='lightgreen'),\n",
        "    row=1, col=1\n",
        ")\n",
        "\n",
        "# Chart 2: Percentage change\n",
        "colors = ['green' if x > 10 else 'orange' if x > 5 else 'red' \n",
        "          for x in sector_comp_df['change_pct']]\n",
        "fig.add_trace(\n",
        "    go.Bar(x=sector_comp_df['sector'], y=sector_comp_df['change_pct'],\n",
        "           marker_color=colors, text=sector_comp_df['change_pct'],\n",
        "           texttemplate='%{text:.1f}%', textposition='outside'),\n",
        "    row=1, col=2\n",
        ")\n",
        "\n",
        "# Chart 3: Fiscal indicators\n",
        "fig.add_trace(\n",
        "    go.Bar(name='2023-24', x=fiscal_comp_df['indicator'], y=fiscal_comp_df['value_2023'],\n",
        "           marker_color='coral'),\n",
        "    row=2, col=1\n",
        ")\n",
        "fig.add_trace(\n",
        "    go.Bar(name='2024-25', x=fiscal_comp_df['indicator'], y=fiscal_comp_df['value_2024'],\n",
        "           marker_color='lightcoral'),\n",
        "    row=2, col=1\n",
        ")\n",
        "\n",
        "# Chart 4: Growth trend\n",
        "years = ['2023-24', '2024-25']\n",
        "total_budgets = [45.0, 47.66]\n",
        "fig.add_trace(\n",
        "    go.Scatter(x=years, y=total_budgets, mode='lines+markers+text',\n",
        "               marker=dict(size=15, color='blue'),\n",
        "               line=dict(color='blue', width=3),\n",
        "               text=total_budgets, textposition='top center'),\n",
        "    row=2, col=2\n",
        ")\n",
        "\n",
        "# Chart 5: Top gainers\n",
        "top_gainers = sector_comp_df.nlargest(5, 'change_pct')\n",
        "fig.add_trace(\n",
        "    go.Bar(x=top_gainers['change_pct'], y=top_gainers['sector'],\n",
        "           orientation='h', marker_color='green'),\n",
        "    row=3, col=1\n",
        ")\n",
        "\n",
        "# Chart 6: Budget distribution pie\n",
        "fig.add_trace(\n",
        "    go.Pie(labels=sector_comp_df['sector'], values=sector_comp_df['budget_2024'],\n",
        "           hole=0.3),\n",
        "    row=3, col=2\n",
        ")\n",
        "\n",
        "fig.update_layout(height=1400, title_text=\"Budget Comparison Analysis: 2023-24 vs 2024-25\")\n",
        "fig.update_xaxes(tickangle=-45, row=1, col=1)\n",
        "fig.update_xaxes(tickangle=-45, row=1, col=2)\n",
        "fig.update_xaxes(tickangle=-45, row=2, col=1)\n",
        "fig.show()\n",
        "\n",
        "# Statistical analysis\n",
        "print(\"\\n📊 COMPARISON STATISTICS:\")\n",
        "print(f\"Average Sector Growth: {sector_comp_df['change_pct'].mean():.2f}%\")\n",
        "print(f\"Highest Growth Sector: {sector_comp_df.loc[sector_comp_df['change_pct'].idxmax(), 'sector']} ({sector_comp_df['change_pct'].max():.1f}%)\")\n",
        "print(f\"Lowest Growth Sector: {sector_comp_df.loc[sector_comp_df['change_pct'].idxmin(), 'sector']} ({sector_comp_df['change_pct'].min():.1f}%)\")\n",
        "print(f\"Total Budget Increase: ₹{(47.66 - 45.0):.2f} lakh crore ({((47.66/45.0 - 1) * 100):.1f}%)\")\n",
        "print(f\"Fiscal Deficit Improvement: {abs(fiscal_comp_df.loc[0, 'change']):.1f} percentage points\")"
    ]
})

# Save progress
with open('NLP.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print("\\n✅ Part 3 completed: Added Financial Docs, Newspaper, and Comparison Analysis")
print("📊 Cells 12-14 added successfully")
