"""
Add Domain-Specific Analysis for all 5 domains
"""

import json

# Load existing notebook
with open('NLP.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Cell 9: Domain 1 - Financial Budget Analysis
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 💰 6. Domain 1: Financial Budget Analysis\n",
        "\n",
        "### NLP Techniques: Pattern Matching, Information Extraction, Entity Linking\n",
        "\n",
        "Extracting sector allocations, fiscal indicators, and economic metrics from budget documents."
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Extract financial data\n",
        "financial_data = extract_financial_data(sentences)\n",
        "\n",
        "print(\"\\n💰 FINANCIAL BUDGET EXTRACTION RESULTS\")\n",
        "print(\"=\" * 70)\n",
        "print(f\"Sector Allocations Extracted: {len(financial_data['sector_allocations'])}\")\n",
        "print(f\"Fiscal Indicators Found: {len(financial_data['fiscal_indicators'])}\")\n",
        "print(f\"Economic Indicators Found: {len(financial_data['economic_indicators'])}\")\n",
        "print(f\"Top Sectors Identified: {len(financial_data['top_sectors'])}\")\n",
        "\n",
        "# Create DataFrames\n",
        "sectors_df = pd.DataFrame(financial_data['sector_allocations'])\n",
        "fiscal_df = pd.DataFrame(financial_data['fiscal_indicators'])\n",
        "top_sectors_df = pd.DataFrame(financial_data['top_sectors'])\n",
        "\n",
        "# Display top sectors\n",
        "print(\"\\n📊 TOP 15 SECTORS BY ALLOCATION:\")\n",
        "if not top_sectors_df.empty:\n",
        "    print(top_sectors_df.head(15).to_string(index=False))\n",
        "    \n",
        "    # Calculate total allocation\n",
        "    total_allocation = top_sectors_df['total_crore'].sum()\n",
        "    print(f\"\\n💵 Total Identified Allocation: ₹{total_allocation:,.2f} crore\")\n",
        "\n",
        "# Display fiscal indicators\n",
        "print(\"\\n📈 KEY FISCAL INDICATORS:\")\n",
        "if not fiscal_df.empty:\n",
        "    fiscal_summary = fiscal_df[['indicator', 'amount_crore', 'percent', 'confidence']].head(10)\n",
        "    print(fiscal_summary.to_string(index=False))\n",
        "\n",
        "# Comprehensive Visualizations\n",
        "fig = make_subplots(\n",
        "    rows=3, cols=2,\n",
        "    subplot_titles=('Top 10 Sectors by Allocation', 'Sector Allocation Distribution',\n",
        "                    'Fiscal Indicators Overview', 'Allocation Confidence Scores',\n",
        "                    'Sector-wise Allocation Treemap', 'Extraction Quality Metrics'),\n",
        "    specs=[[{'type': 'bar'}, {'type': 'pie'}],\n",
        "           [{'type': 'bar'}, {'type': 'box'}],\n",
        "           [{'type': 'treemap', 'colspan': 2}, None]],\n",
        "    row_heights=[0.3, 0.3, 0.4]\n",
        ")\n",
        "\n",
        "# Chart 1: Top 10 sectors bar chart\n",
        "if not top_sectors_df.empty:\n",
        "    top_10 = top_sectors_df.head(10)\n",
        "    fig.add_trace(\n",
        "        go.Bar(x=top_10['sector'], y=top_10['total_crore'],\n",
        "               marker_color='lightblue', text=top_10['total_crore'],\n",
        "               texttemplate='₹%{text:,.0f}Cr', textposition='outside'),\n",
        "        row=1, col=1\n",
        "    )\n",
        "\n",
        "# Chart 2: Pie chart of allocation distribution\n",
        "if not top_sectors_df.empty:\n",
        "    top_8 = top_sectors_df.head(8)\n",
        "    fig.add_trace(\n",
        "        go.Pie(labels=top_8['sector'], values=top_8['total_crore'],\n",
        "               hole=0.3),\n",
        "        row=1, col=2\n",
        "    )\n",
        "\n",
        "# Chart 3: Fiscal indicators\n",
        "if not fiscal_df.empty:\n",
        "    fiscal_top = fiscal_df.head(8)\n",
        "    fig.add_trace(\n",
        "        go.Bar(x=fiscal_top['indicator'], y=fiscal_top['amount_crore'],\n",
        "               marker_color='lightgreen'),\n",
        "        row=2, col=1\n",
        "    )\n",
        "\n",
        "# Chart 4: Confidence score distribution\n",
        "if not sectors_df.empty and 'confidence' in sectors_df.columns:\n",
        "    fig.add_trace(\n",
        "        go.Box(y=sectors_df['confidence'], name='Confidence',\n",
        "               marker_color='lightcoral'),\n",
        "        row=2, col=2\n",
        "    )\n",
        "\n",
        "# Chart 5: Treemap of allocations\n",
        "if not top_sectors_df.empty:\n",
        "    fig.add_trace(\n",
        "        go.Treemap(\n",
        "            labels=top_sectors_df['sector'][:15],\n",
        "            parents=[''] * len(top_sectors_df[:15]),\n",
        "            values=top_sectors_df['total_crore'][:15],\n",
        "            textinfo='label+value+percent parent',\n",
        "            marker=dict(colorscale='Blues')\n",
        "        ),\n",
        "        row=3, col=1\n",
        "    )\n",
        "\n",
        "fig.update_xaxes(title_text=\"Sector\", row=1, col=1, tickangle=-45)\n",
        "fig.update_yaxes(title_text=\"Allocation (Crore ₹)\", row=1, col=1)\n",
        "fig.update_xaxes(title_text=\"Indicator\", row=2, col=1, tickangle=-45)\n",
        "fig.update_yaxes(title_text=\"Amount (Crore ₹)\", row=2, col=1)\n",
        "fig.update_yaxes(title_text=\"Confidence Score\", row=2, col=2)\n",
        "\n",
        "fig.update_layout(height=1200, showlegend=False, \n",
        "                  title_text=\"Financial Budget Analysis - Comprehensive View\")\n",
        "fig.show()\n",
        "\n",
        "# Statistical Analysis\n",
        "if not sectors_df.empty:\n",
        "    print(\"\\n📊 STATISTICAL SUMMARY - SECTOR ALLOCATIONS:\")\n",
        "    print(f\"Mean Allocation: ₹{sectors_df['amount_crore'].mean():,.2f} crore\")\n",
        "    print(f\"Median Allocation: ₹{sectors_df['amount_crore'].median():,.2f} crore\")\n",
        "    print(f\"Std Deviation: ₹{sectors_df['amount_crore'].std():,.2f} crore\")\n",
        "    print(f\"Min Allocation: ₹{sectors_df['amount_crore'].min():,.2f} crore\")\n",
        "    print(f\"Max Allocation: ₹{sectors_df['amount_crore'].max():,.2f} crore\")\n",
        "    \n",
        "    if 'confidence' in sectors_df.columns:\n",
        "        print(f\"\\nAverage Extraction Confidence: {sectors_df['confidence'].mean():.1f}%\")\n",
        "        print(f\"High Confidence Extractions (>80%): {(sectors_df['confidence'] > 80).sum()}\")"
    ]
})

# Cell 10: Policy & Tax Extraction
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Extract policy and tax data\n",
        "policy_data = extract_policy_data(sentences)\n",
        "tax_data = extract_tax_data(sentences)\n",
        "\n",
        "print(\"\\n📜 POLICY & TAX EXTRACTION RESULTS\")\n",
        "print(\"=\" * 70)\n",
        "print(f\"Policy Schemes Identified: {len(policy_data.get('schemes', []))}\")\n",
        "print(f\"Policy Initiatives Found: {len(policy_data.get('initiatives', []))}\")\n",
        "print(f\"Tax Changes Detected: {len(tax_data.get('tax_changes', []))}\")\n",
        "print(f\"Tax Slabs Identified: {len(tax_data.get('tax_slabs', []))}\")\n",
        "\n",
        "# Display policy schemes\n",
        "schemes = policy_data.get('schemes', [])\n",
        "if schemes:\n",
        "    print(\"\\n🎯 TOP POLICY SCHEMES:\")\n",
        "    schemes_df = pd.DataFrame(schemes[:10])\n",
        "    if not schemes_df.empty:\n",
        "        print(schemes_df[['scheme_name', 'category', 'confidence']].to_string(index=False))\n",
        "\n",
        "# Display tax changes\n",
        "tax_changes = tax_data.get('tax_changes', [])\n",
        "if tax_changes:\n",
        "    print(\"\\n💸 TAX CHANGES IDENTIFIED:\")\n",
        "    tax_df = pd.DataFrame(tax_changes[:10])\n",
        "    if not tax_df.empty:\n",
        "        print(tax_df[['tax_type', 'change_description', 'confidence']].to_string(index=False))\n",
        "\n",
        "# Visualize policy and tax data\n",
        "fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n",
        "\n",
        "# Chart 1: Policy schemes by category\n",
        "if schemes:\n",
        "    categories = [s.get('category', 'Other') for s in schemes]\n",
        "    cat_counts = Counter(categories)\n",
        "    axes[0, 0].bar(cat_counts.keys(), cat_counts.values(), color='skyblue', edgecolor='black')\n",
        "    axes[0, 0].set_title('Policy Schemes by Category', fontweight='bold')\n",
        "    axes[0, 0].set_xlabel('Category')\n",
        "    axes[0, 0].set_ylabel('Count')\n",
        "    axes[0, 0].tick_params(axis='x', rotation=45)\n",
        "    axes[0, 0].grid(axis='y', alpha=0.3)\n",
        "\n",
        "# Chart 2: Tax changes by type\n",
        "if tax_changes:\n",
        "    tax_types = [t.get('tax_type', 'Other') for t in tax_changes]\n",
        "    tax_counts = Counter(tax_types)\n",
        "    axes[0, 1].barh(list(tax_counts.keys()), list(tax_counts.values()), \n",
        "                    color='lightgreen', edgecolor='black')\n",
        "    axes[0, 1].set_title('Tax Changes by Type', fontweight='bold')\n",
        "    axes[0, 1].set_xlabel('Count')\n",
        "    axes[0, 1].grid(axis='x', alpha=0.3)\n",
        "\n",
        "# Chart 3: Confidence distribution for policies\n",
        "if schemes:\n",
        "    confidences = [s.get('confidence', 70) for s in schemes]\n",
        "    axes[1, 0].hist(confidences, bins=15, color='coral', alpha=0.7, edgecolor='black')\n",
        "    axes[1, 0].axvline(np.mean(confidences), color='red', linestyle='--', \n",
        "                       linewidth=2, label=f'Mean: {np.mean(confidences):.1f}%')\n",
        "    axes[1, 0].set_title('Policy Extraction Confidence Distribution', fontweight='bold')\n",
        "    axes[1, 0].set_xlabel('Confidence Score')\n",
        "    axes[1, 0].set_ylabel('Frequency')\n",
        "    axes[1, 0].legend()\n",
        "    axes[1, 0].grid(axis='y', alpha=0.3)\n",
        "\n",
        "# Chart 4: Tax vs Policy extraction comparison\n",
        "extraction_counts = {\n",
        "    'Policy Schemes': len(schemes),\n",
        "    'Policy Initiatives': len(policy_data.get('initiatives', [])),\n",
        "    'Tax Changes': len(tax_changes),\n",
        "    'Tax Slabs': len(tax_data.get('tax_slabs', []))\n",
        "}\n",
        "axes[1, 1].bar(extraction_counts.keys(), extraction_counts.values(), \n",
        "               color=['#3498db', '#2ecc71', '#e74c3c', '#f39c12'], edgecolor='black')\n",
        "axes[1, 1].set_title('Extraction Summary: Policy vs Tax', fontweight='bold')\n",
        "axes[1, 1].set_ylabel('Count')\n",
        "axes[1, 1].tick_params(axis='x', rotation=45)\n",
        "axes[1, 1].grid(axis='y', alpha=0.3)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()"
    ]
})

# Cell 11: Domain 2 - Economic Survey Analysis
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 📈 7. Domain 2: Economic Survey Analysis\n",
        "\n",
        "### NLP Techniques: Macro-Economic Indicator Extraction, Trend Analysis\n",
        "\n",
        "Extracting GDP, inflation, sector performance, and policy recommendations."
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Sample economic survey text\n",
        "economic_text = \"\"\"\n",
        "The Indian economy demonstrated resilience with GDP growth of 7.2 percent in FY 2023-24.\n",
        "Inflation moderated to 5.4 percent, within the RBI's target range.\n",
        "Agriculture sector grew by 4.0 percent, contributing significantly to rural income.\n",
        "Industrial production increased by 5.8 percent, led by manufacturing growth.\n",
        "Services sector expanded by 8.5 percent, driven by IT and financial services.\n",
        "Unemployment rate declined to 6.1 percent from 7.3 percent last year.\n",
        "Foreign exchange reserves reached USD 625 billion, providing economic stability.\n",
        "Exports grew by 9.2 percent to USD 450 billion, improving trade balance.\n",
        "The government recommends continued focus on infrastructure investment.\n",
        "Policy emphasis on digital transformation and skill development is crucial.\n",
        "Fiscal consolidation should be pursued while maintaining growth momentum.\n",
        "\"\"\"\n",
        "\n",
        "# Process economic survey text\n",
        "econ_sentences = segment_sentences(normalize_text(clean_text(economic_text, \"English\")), \"English\")\n",
        "economic_data = extract_economic_survey_data(econ_sentences)\n",
        "\n",
        "print(\"\\n📈 ECONOMIC SURVEY EXTRACTION RESULTS\")\n",
        "print(\"=\" * 70)\n",
        "print(f\"Macro Indicators Found: {len(economic_data.get('macro_indicators', []))}\")\n",
        "print(f\"Sector Performance Data: {len(economic_data.get('sector_performance', []))}\")\n",
        "print(f\"Policy Recommendations: {len(economic_data.get('recommendations', []))}\")\n",
        "\n",
        "# Display macro indicators\n",
        "macro_indicators = economic_data.get('macro_indicators', [])\n",
        "if macro_indicators:\n",
        "    print(\"\\n📊 KEY MACRO-ECONOMIC INDICATORS:\")\n",
        "    macro_df = pd.DataFrame(macro_indicators)\n",
        "    print(macro_df.to_string(index=False))\n",
        "\n",
        "# Display sector performance\n",
        "sector_perf = economic_data.get('sector_performance', [])\n",
        "if sector_perf:\n",
        "    print(\"\\n🏭 SECTOR PERFORMANCE:\")\n",
        "    sector_df = pd.DataFrame(sector_perf)\n",
        "    print(sector_df.to_string(index=False))\n",
        "\n",
        "# Visualizations\n",
        "fig = make_subplots(\n",
        "    rows=2, cols=2,\n",
        "    subplot_titles=('Macro-Economic Indicators', 'Sector Growth Rates',\n",
        "                    'Economic Metrics Comparison', 'Policy Recommendations'),\n",
        "    specs=[[{'type': 'bar'}, {'type': 'bar'}],\n",
        "           [{'type': 'scatter'}, {'type': 'table'}]]\n",
        ")\n",
        "\n",
        "# Chart 1: Macro indicators\n",
        "if macro_indicators:\n",
        "    indicators = [m['indicator'] for m in macro_indicators]\n",
        "    values = [float(m['value']) for m in macro_indicators]\n",
        "    fig.add_trace(\n",
        "        go.Bar(x=indicators, y=values, marker_color='lightblue',\n",
        "               text=values, textposition='outside'),\n",
        "        row=1, col=1\n",
        "    )\n",
        "\n",
        "# Chart 2: Sector growth\n",
        "if sector_perf:\n",
        "    sectors = [s['sector'] for s in sector_perf]\n",
        "    growth = [float(s.get('growth_rate', 0)) for s in sector_perf]\n",
        "    colors = ['green' if g > 5 else 'orange' if g > 3 else 'red' for g in growth]\n",
        "    fig.add_trace(\n",
        "        go.Bar(x=sectors, y=growth, marker_color=colors),\n",
        "        row=1, col=2\n",
        "    )\n",
        "\n",
        "# Chart 3: Scatter plot of indicators\n",
        "if macro_indicators:\n",
        "    fig.add_trace(\n",
        "        go.Scatter(x=list(range(len(indicators))), y=values,\n",
        "                   mode='lines+markers', marker=dict(size=12, color='coral'),\n",
        "                   line=dict(color='blue', width=2)),\n",
        "        row=2, col=1\n",
        "    )\n",
        "\n",
        "# Chart 4: Recommendations table\n",
        "recommendations = economic_data.get('recommendations', [])\n",
        "if recommendations:\n",
        "    rec_text = [r.get('recommendation', '')[:60] + '...' for r in recommendations[:5]]\n",
        "    fig.add_trace(\n",
        "        go.Table(\n",
        "            header=dict(values=['Policy Recommendations'],\n",
        "                       fill_color='paleturquoise',\n",
        "                       align='left'),\n",
        "            cells=dict(values=[rec_text],\n",
        "                      fill_color='lavender',\n",
        "                      align='left')\n",
        "        ),\n",
        "        row=2, col=2\n",
        "    )\n",
        "\n",
        "fig.update_layout(height=900, showlegend=False,\n",
        "                  title_text=\"Economic Survey Analysis\")\n",
        "fig.show()\n",
        "\n",
        "# Statistical summary\n",
        "if macro_indicators:\n",
        "    print(\"\\n📊 ECONOMIC STATISTICS:\")\n",
        "    print(f\"Average Growth Rate: {np.mean([float(m['value']) for m in macro_indicators if 'growth' in m['indicator'].lower()]):.2f}%\")\n",
        "    print(f\"Total Indicators Tracked: {len(macro_indicators)}\")\n",
        "    print(f\"Sectors Analyzed: {len(sector_perf)}\")"
    ]
})

# Save progress
with open('NLP.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print("\\n✅ Part 2 completed: Added Budget & Economic Survey Analysis")
print("📊 Cells 9-11 added successfully")
