"""
Complete NLP Analysis Notebook Generator - All Domains
Adds all remaining cells with comprehensive analysis
"""

import json

# Load existing notebook
with open('NLP.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Continue adding cells...

# Cell 6: Named Entity Recognition Analysis
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 🏷️ 3. Named Entity Recognition (NER) Analysis\n",
        "\n",
        "### NLP Technique: Information Extraction using Rule-Based NER\n",
        "\n",
        "Extracting entities: Organizations, Locations, Monetary Values, Dates, Sectors, Fiscal Terms"
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Extract entities using rule-based NER\n",
        "entities = extract_entities(sentences)\n",
        "monetary_values = extract_monetary_values(sentences)\n",
        "\n",
        "# Entity Statistics\n",
        "ner_stats = {\n",
        "    \"Organizations\": len(entities.get('organizations', [])),\n",
        "    \"Locations\": len(entities.get('locations', [])),\n",
        "    \"Dates\": len(entities.get('dates', [])),\n",
        "    \"Monetary Values\": len(entities.get('money', [])),\n",
        "    \"Percentages\": len(entities.get('percentages', [])),\n",
        "    \"Sectors Mentioned\": len(entities.get('sectors', [])),\n",
        "    \"Fiscal Terms\": len(entities.get('fiscal_terms', []))\n",
        "}\n",
        "\n",
        "print(\"\\n🏷️ NAMED ENTITY RECOGNITION RESULTS\")\n",
        "print(\"=\" * 60)\n",
        "for entity_type, count in ner_stats.items():\n",
        "    print(f\"{entity_type:.<40} {count:>5}\")\n",
        "\n",
        "# Create visualizations\n",
        "fig = make_subplots(\n",
        "    rows=2, cols=2,\n",
        "    subplot_titles=('Entity Type Distribution', 'Top Organizations', \n",
        "                    'Top Locations', 'Monetary Value Distribution'),\n",
        "    specs=[[{'type': 'bar'}, {'type': 'bar'}],\n",
        "           [{'type': 'bar'}, {'type': 'histogram'}]]\n",
        ")\n",
        "\n",
        "# Chart 1: Entity type distribution\n",
        "fig.add_trace(\n",
        "    go.Bar(x=list(ner_stats.keys()), y=list(ner_stats.values()),\n",
        "           marker_color='lightblue', name='Entity Count'),\n",
        "    row=1, col=1\n",
        ")\n",
        "\n",
        "# Chart 2: Top organizations\n",
        "orgs = entities.get('organizations', [])[:10]\n",
        "org_counts = Counter(orgs)\n",
        "if org_counts:\n",
        "    fig.add_trace(\n",
        "        go.Bar(x=list(org_counts.values()), y=list(org_counts.keys()),\n",
        "               orientation='h', marker_color='lightgreen', name='Organizations'),\n",
        "        row=1, col=2\n",
        "    )\n",
        "\n",
        "# Chart 3: Top locations\n",
        "locs = entities.get('locations', [])[:10]\n",
        "loc_counts = Counter(locs)\n",
        "if loc_counts:\n",
        "    fig.add_trace(\n",
        "        go.Bar(x=list(loc_counts.values()), y=list(loc_counts.keys()),\n",
        "               orientation='h', marker_color='lightcoral', name='Locations'),\n",
        "        row=2, col=1\n",
        "    )\n",
        "\n",
        "# Chart 4: Monetary value distribution (histogram)\n",
        "money_values = [m.get('value_text', '') for m in monetary_values[:50]]\n",
        "if money_values:\n",
        "    fig.add_trace(\n",
        "        go.Histogram(x=list(range(len(money_values))), \n",
        "                     marker_color='gold', name='Monetary Mentions'),\n",
        "        row=2, col=2\n",
        "    )\n",
        "\n",
        "fig.update_layout(height=800, showlegend=False, title_text=\"Named Entity Recognition Analysis\")\n",
        "fig.show()\n",
        "\n",
        "# Display sample entities\n",
        "print(\"\\n📋 SAMPLE EXTRACTED ENTITIES:\")\n",
        "print(\"\\nOrganizations:\", entities.get('organizations', [])[:5])\n",
        "print(\"Locations:\", entities.get('locations', [])[:5])\n",
        "print(\"Dates:\", entities.get('dates', [])[:5])\n",
        "print(\"\\nSample Monetary Values:\")\n",
        "for mv in monetary_values[:5]:\n",
        "    print(f\"  • {mv['value_text']} - {mv['sentence'][:80]}...\")"
    ]
})

# Cell 7: Sentiment Analysis
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 😊 4. Sentiment Analysis\n",
        "\n",
        "### NLP Technique: Lexicon-Based Sentiment Analysis\n",
        "\n",
        "Analyzing the overall tone and sentiment of the budget speech using domain-specific lexicons."
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Perform sentiment analysis\n",
        "sentiment_result = analyze_sentiment(normalized_text)\n",
        "\n",
        "print(\"\\n😊 SENTIMENT ANALYSIS RESULTS\")\n",
        "print(\"=\" * 60)\n",
        "print(f\"Overall Sentiment: {sentiment_result['label']}\")\n",
        "print(f\"Sentiment Score: {sentiment_result['score']:.3f} (Range: -1 to +1)\")\n",
        "print(f\"Positive Sentences: {sentiment_result['positive']} ({sentiment_result['positive']/sentiment_result['total']*100:.1f}%)\")\n",
        "print(f\"Negative Sentences: {sentiment_result['negative']} ({sentiment_result['negative']/sentiment_result['total']*100:.1f}%)\")\n",
        "print(f\"Neutral Sentences: {sentiment_result['neutral']} ({sentiment_result['neutral']/sentiment_result['total']*100:.1f}%)\")\n",
        "print(f\"Total Sentences Analyzed: {sentiment_result['total']}\")\n",
        "\n",
        "# Create comprehensive sentiment visualizations\n",
        "fig = make_subplots(\n",
        "    rows=2, cols=2,\n",
        "    subplot_titles=('Sentiment Distribution', 'Sentiment Score Gauge',\n",
        "                    'Sentence-Level Sentiment Trend', 'Sentiment Breakdown'),\n",
        "    specs=[[{'type': 'pie'}, {'type': 'indicator'}],\n",
        "           [{'type': 'scatter'}, {'type': 'bar'}]]\n",
        ")\n",
        "\n",
        "# Chart 1: Pie chart of sentiment distribution\n",
        "sentiment_counts = [sentiment_result['positive'], sentiment_result['negative'], sentiment_result['neutral']]\n",
        "sentiment_labels = ['Positive', 'Negative', 'Neutral']\n",
        "colors = ['#2ECC71', '#E74C3C', '#95A5A6']\n",
        "\n",
        "fig.add_trace(\n",
        "    go.Pie(labels=sentiment_labels, values=sentiment_counts, \n",
        "           marker=dict(colors=colors), hole=0.3),\n",
        "    row=1, col=1\n",
        ")\n",
        "\n",
        "# Chart 2: Gauge chart for overall sentiment score\n",
        "fig.add_trace(\n",
        "    go.Indicator(\n",
        "        mode=\"gauge+number+delta\",\n",
        "        value=sentiment_result['score'],\n",
        "        domain={'x': [0, 1], 'y': [0, 1]},\n",
        "        title={'text': \"Sentiment Score\"},\n",
        "        delta={'reference': 0},\n",
        "        gauge={\n",
        "            'axis': {'range': [-1, 1]},\n",
        "            'bar': {'color': \"darkblue\"},\n",
        "            'steps': [\n",
        "                {'range': [-1, -0.3], 'color': \"#E74C3C\"},\n",
        "                {'range': [-0.3, 0.3], 'color': \"#95A5A6\"},\n",
        "                {'range': [0.3, 1], 'color': \"#2ECC71\"}],\n",
        "            'threshold': {\n",
        "                'line': {'color': \"red\", 'width': 4},\n",
        "                'thickness': 0.75,\n",
        "                'value': sentiment_result['score']}\n",
        "        }\n",
        "    ),\n",
        "    row=1, col=2\n",
        ")\n",
        "\n",
        "# Chart 3: Sentence-level sentiment trend\n",
        "breakdown = sentiment_result.get('breakdown', [])[:50]  # First 50 sentences\n",
        "if breakdown:\n",
        "    sent_scores = [b['score'] for b in breakdown]\n",
        "    sent_indices = list(range(len(sent_scores)))\n",
        "    sent_colors = ['green' if s > 0.1 else 'red' if s < -0.1 else 'gray' for s in sent_scores]\n",
        "    \n",
        "    fig.add_trace(\n",
        "        go.Scatter(x=sent_indices, y=sent_scores, mode='lines+markers',\n",
        "                   marker=dict(color=sent_colors, size=6),\n",
        "                   line=dict(color='blue', width=1),\n",
        "                   name='Sentiment Trend'),\n",
        "        row=2, col=1\n",
        "    )\n",
        "    fig.add_hline(y=0, line_dash=\"dash\", line_color=\"black\", row=2, col=1)\n",
        "\n",
        "# Chart 4: Bar chart comparing positive vs negative hits\n",
        "if breakdown:\n",
        "    total_pos_hits = sum(b['pos_hits'] for b in breakdown)\n",
        "    total_neg_hits = sum(b['neg_hits'] for b in breakdown)\n",
        "    \n",
        "    fig.add_trace(\n",
        "        go.Bar(x=['Positive Words', 'Negative Words'], \n",
        "               y=[total_pos_hits, total_neg_hits],\n",
        "               marker_color=['#2ECC71', '#E74C3C']),\n",
        "        row=2, col=2\n",
        "    )\n",
        "\n",
        "fig.update_layout(height=900, showlegend=False, title_text=\"Comprehensive Sentiment Analysis\")\n",
        "fig.show()\n",
        "\n",
        "# Display sample sentiment breakdown\n",
        "print(\"\\n📊 SAMPLE SENTENCE-LEVEL SENTIMENT:\")\n",
        "for i, item in enumerate(breakdown[:5], 1):\n",
        "    print(f\"\\n{i}. Sentence: {item['sentence']}\")\n",
        "    print(f\"   Label: {item['label']} | Score: {item['score']:.3f} | Pos: {item['pos_hits']} | Neg: {item['neg_hits']}\")"
    ]
})

# Cell 8: Keyword Extraction & TF-IDF
notebook["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 🔤 5. Keyword Extraction & TF-IDF Analysis\n",
        "\n",
        "### NLP Techniques: TF-IDF, Keyword Scoring, Domain Boosting\n",
        "\n",
        "Identifying the most important keywords and ranking sentences by relevance."
    ]
})

notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Extract top keywords\n",
        "top_keywords = get_top_keywords(sentences, top_n=40)\n",
        "\n",
        "# Rank sentences by importance\n",
        "ranked_sentences = rank_sentences(sentences, top_n=20)\n",
        "\n",
        "print(\"\\n🔤 KEYWORD EXTRACTION RESULTS\")\n",
        "print(\"=\" * 60)\n",
        "print(f\"Total Keywords Extracted: {len(top_keywords)}\")\n",
        "print(f\"Top Ranked Sentences: {len(ranked_sentences)}\")\n",
        "\n",
        "# Create keyword DataFrame\n",
        "keywords_df = pd.DataFrame(top_keywords)\n",
        "print(\"\\n📊 TOP 20 KEYWORDS:\")\n",
        "print(keywords_df.head(20).to_string(index=False))\n",
        "\n",
        "# Visualizations\n",
        "fig = make_subplots(\n",
        "    rows=2, cols=2,\n",
        "    subplot_titles=('Top 15 Keywords by Score', 'Keyword Frequency Distribution',\n",
        "                    'Domain Boost Impact', 'TF-IDF vs Frequency'),\n",
        "    specs=[[{'type': 'bar'}, {'type': 'bar'}],\n",
        "           [{'type': 'scatter'}, {'type': 'scatter'}]]\n",
        ")\n",
        "\n",
        "# Chart 1: Top keywords by score\n",
        "top_15 = keywords_df.head(15)\n",
        "fig.add_trace(\n",
        "    go.Bar(x=top_15['score'], y=top_15['keyword'], orientation='h',\n",
        "           marker_color='lightblue', text=top_15['score'],\n",
        "           textposition='outside'),\n",
        "    row=1, col=1\n",
        ")\n",
        "\n",
        "# Chart 2: Keyword frequency\n",
        "fig.add_trace(\n",
        "    go.Bar(x=top_15['keyword'], y=top_15['frequency'],\n",
        "           marker_color='lightgreen'),\n",
        "    row=1, col=2\n",
        ")\n",
        "\n",
        "# Chart 3: Domain boost impact\n",
        "fig.add_trace(\n",
        "    go.Scatter(x=keywords_df['frequency'][:30], y=keywords_df['boost'][:30],\n",
        "               mode='markers', marker=dict(size=10, color=keywords_df['score'][:30],\n",
        "                                          colorscale='Viridis', showscale=True),\n",
        "               text=keywords_df['keyword'][:30]),\n",
        "    row=2, col=1\n",
        ")\n",
        "\n",
        "# Chart 4: Score vs Frequency correlation\n",
        "fig.add_trace(\n",
        "    go.Scatter(x=keywords_df['frequency'][:30], y=keywords_df['score'][:30],\n",
        "               mode='markers+text', marker=dict(size=12, color='coral'),\n",
        "               text=keywords_df['keyword'][:30], textposition='top center'),\n",
        "    row=2, col=2\n",
        ")\n",
        "\n",
        "fig.update_xaxes(title_text=\"Score\", row=1, col=1)\n",
        "fig.update_xaxes(title_text=\"Keyword\", row=1, col=2)\n",
        "fig.update_xaxes(title_text=\"Frequency\", row=2, col=1)\n",
        "fig.update_xaxes(title_text=\"Frequency\", row=2, col=2)\n",
        "fig.update_yaxes(title_text=\"Keyword\", row=1, col=1)\n",
        "fig.update_yaxes(title_text=\"Frequency\", row=1, col=2)\n",
        "fig.update_yaxes(title_text=\"Boost Factor\", row=2, col=1)\n",
        "fig.update_yaxes(title_text=\"Score\", row=2, col=2)\n",
        "\n",
        "fig.update_layout(height=900, showlegend=False, title_text=\"Keyword Extraction & TF-IDF Analysis\")\n",
        "fig.show()\n",
        "\n",
        "# Word Cloud\n",
        "print(\"\\n☁️ Generating Word Cloud...\")\n",
        "wordcloud_text = ' '.join([kw['keyword'] for kw in top_keywords for _ in range(kw['frequency'])])\n",
        "wordcloud = WordCloud(width=1200, height=600, background_color='white',\n",
        "                      colormap='viridis', max_words=100).generate(wordcloud_text)\n",
        "\n",
        "plt.figure(figsize=(15, 8))\n",
        "plt.imshow(wordcloud, interpolation='bilinear')\n",
        "plt.axis('off')\n",
        "plt.title('Budget Speech Word Cloud - Top Keywords', fontsize=16, fontweight='bold')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "# Display top ranked sentences\n",
        "print(\"\\n📝 TOP 5 MOST IMPORTANT SENTENCES (by TF-IDF + Domain Boost):\")\n",
        "for i, sent_data in enumerate(ranked_sentences[:5], 1):\n",
        "    print(f\"\\n{i}. [Score: {sent_data['score']:.4f}] {sent_data['sentence'][:150]}...\")"
    ]
})

# Save updated notebook
with open('NLP.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print("\\n✅ Part 1 of NLP notebook completed (Cells 1-8)")
print("📊 Added: Preprocessing, NER, Sentiment, Keywords")
